# Generated by Django 4.1.4 on 2022-12-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.FileField(null=True, upload_to='groups/'),
        ),
    ]
